<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>RangeCrafting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ClaimLinkedCrafting.cs" />
    <Compile Include="ModConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>C:\\Users\\Yong Wei\\.nuget\\packages\\lib.harmony\\2.3.3\\lib\\net48\\0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>S:\\SteamLibrary\\steamapps\\common\\7 Days To Die\\7DaysToDie_Data\\Managed\\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>S:\\SteamLibrary\\steamapps\\common\\7 Days To Die\\7DaysToDie_Data\\Managed\\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>S:\\SteamLibrary\\steamapps\\common\\7 Days To Die\\7DaysToDie_Data\\Managed\\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
