<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>RangeCrafting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ClaimLinkedCrafting.cs" />
    <Compile Include="ModConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\\..\\..\\path\\to\\7d2d\\lib\\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\\..\\..\\path\\to\\7d2d\\7DaysToDie_Data\\Managed\\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\\..\\..\\path\\to\\7d2d\\7DaysToDie_Data\\Managed\\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\\..\\..\\path\\to\\7d2d\\7DaysToDie_Data\\Managed\\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Platform">
      <HintPath>..\\..\\..\\path\\to\\7d2d\\7DaysToDie_Data\\Managed\\Platform.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
